---
- name: Maak gebruikers aan, genereer SSH-sleutels en maak LXC-containers aan
  hosts: proxmox1
  become: yes
  vars:
    users:
      - name: user1
        ssh_key_path: "/home/user1/.ssh/id_rsa.pub"  # Pad voor publieke sleutel van user1
      - name: user2
        ssh_key_path: "/home/user2/.ssh/id_rsa.pub"  # Pad voor publieke sleutel van user2
    container_name_prefix: "WP"               # Prefix voor container namen
    container_count: 2                        # Aantal containers
    container_disk_size: "30G"                # Grootte rootfs
    container_cpu_cores: 1                    # Aantal CPU cores
    container_memory_size: 1024               # Geheugen in MB
    container_network_speed: 400              # Netwerksnelheid in mbits!
    container_onboot: 1                       # Container automatisch starten
    container_os_template: "local:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst" # OS template
    ceph_pool: "Zwembad"                      # Naam van de Ceph pool

  tasks:
    - name: Maak gebruikers aan
      user:
        name: "{{ item.name }}"
        create_home: yes
      loop: "{{ users }}"

    - name: Maak .ssh directory voor elke gebruiker
      file:
        path: "/home/{{ item.name }}/.ssh"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: "0700"
      loop: "{{ users }}"

    - name: Genereer SSH-sleutels voor elke gebruiker
      command:
        cmd: ssh-keygen -t rsa -b 4096 -f /home/{{ item.name }}/.ssh/id_rsa -q -N ""
        creates: "/home/{{ item.name }}/.ssh/id_rsa"
      loop: "{{ users }}"

    - name: Stel permissies in op de privésleutel voor elke gebruiker
      file:
        path: "/home/{{ item.name }}/.ssh/id_rsa"
        mode: "0600"
      loop: "{{ users }}"

    - name: Maak containers aan
      shell: >
        pct create {{ item }} {{ container_os_template }}
        --hostname {{ container_name_prefix }}-{{ item }}
        --cores {{ container_cpu_cores }}
        --memory {{ container_memory_size }}
        --onboot {{ container_onboot }}
        --net0 name=eth0,bridge=vmbr0,rate={{ container_network_speed }}
        --rootfs {{ ceph_pool }}:{{ item }},size={{ container_disk_size }}
        --ssh-public-keys {{ users[0].ssh_key_path }} --ssh-public-keys {{ users[1].ssh_key_path }}
      loop: "{{ range(1, container_count + 1) | list }}"
      register: container_creation

